x = dt * (1:t_step);
constraint_time = t_step / 2;
state_min = zeros(1,t_step);
state_min(1:constraint_time) = sin(dt * (1:constraint_time)) * 0.4;
state_min(constraint_time:t_step) = 0.35;
state_min = [0 state_min(1:t_step)];
D = 11.4;
v = 0.426;
hfig = figure;
% 2) Create your figure and plot
plot(x, [lam_opt(1:t_step)'] / D, 'LineWidth',3,'Color',[0.8500, 0.3250, 0.0980], 'Marker','o');
% plot(x, [lam_opt(1:t_step)'] * v^2 / D, 'LineWidth',4,'Color',[0.8500, 0.3250, 0.0980], 'Marker','o');

xlim([0.1 1])
% hold on;
% plot(x, cos(x).*exp(-0.1*x), '--', 'LineWidth', 1.5);
% hold off;

% 3) Customize labels and title with font name & size
xlabel('$ \textit{t}$', ...
        'Interpreter','latex', ...
       'FontSize', 25, ...
       'FontName', 'Helvetica', ...
       'FontWeight', 'bold');
ylabel('$\Sigma^*_a\textit{(t)}$', ...
        'Interpreter','latex', ...
       'FontSize', 25, ...
       'FontName', 'Helvetica', ...
       'FontWeight', 'bold');
%'$\lambda^*_c\textit{(t)}$', ...
% $\Sigma^*_a\textit{(t)}$ 

% title('Damped Sinusoid and Cosinusoid', ...
%       'FontSize', 18, ...
%       'FontName', 'Helvetica', ...
%       'FontWeight', 'bold');
% 
% 4) Adjust the axes tick labels
ax = gca;
ax.FontSize   = 25;              % tick-label size
ax.FontName   = 'Arial';         % tick-label font
ax.LineWidth  = 1;               % thickness of box
ax.Box        = 'on';            % draw box around axes
ax.TickLabelInterpreter = 'latex';

% % 5) Optional: set global defaults for all future plots in this session
% set(groot, ...
%     'defaultAxesFontName',   'Arial', ...
%     'defaultAxesFontSize',    14, ...
%     'defaultTextFontName',    'Helvetica', ...
%     'defaultTextFontSize',    16, ...
%     'defaultLineLineWidth',    4);
% 
% Now any new figure you open will inherit these settings!
set(findall(hfig, '-property', 'FontSize'), 'FontSize', 25);
set(findall(hfig, '-property', 'Interpreter'), 'Interpreter', 'Latex');
set(findall(hfig, '-property', 'TickLabelInterpreter'), 'TickLabelInterpreter', 'latex');
set(findall(hfig, '-property', 'LindWidth'), 'LindWidth', 4);
% exportgraphics(gca, '/Users/zhexianli/Dropbox/Apps/Overleaf/Control in mechanics/fig/lambda-nuclear-cos.pdf', ...
%     'BackgroundColor','none', ...
%     'ContentType','vector');